### ISSUE TITLE
The function doesn't return any value

### ISSUE THREAD

**Issue by hoangnamgiavn** [lequan81/vn_lunar#1]
When I ran the sample of this library, this error was happened
```
solar2lunar.cpp:150:1: error: no return statement in function returning non-void [-Werror=return-type]
  150 | }
```
If I change the function to void solar2lunar::convertSolar2Lunar, the error doesn't happen but the result is not correct.
Lich Am Ngay 132997500 Thang 40738548 Nam 2022

Please check again

**Comment by lequan81** [comment]
Hi, thanks for visiting my repo.

Yes, it is a bug in my library/program. I have known that for about 3 years, but it is not my manta, so I just put it in the dust, waiting to be fixed (if it could). The problem with my library is that there is not enough memory to run it properly anymore. When I made this, it worked "just fine" with Arduino Uno and Arduino IDE version 1.18. I believe so. 
And yes, you can tweak the byte size of variables, but as I said, this library and even Arduino are not my mantas anymore. Additionally, this is more or less a POC, a fun project to learn how to make Arduino libs and publish them, because the code for this lunar calculation is way too longggg for such a small thing, and overall, it gave you no more than 30% of the free space left. 

So, what you could do to fix it, or at least make your project "run,"  is look at this [the ugliest piece of code](https://github.com/lequan81/arduino/blob/main/ESP_clock_lunar/ESP_clock_lunar.ino#L381-L518) which I implement and put in my libs. 
I hope this comment will be able to help you at some point. Stay tuned and get creative.

PS: Fell free to make a pull-request 😀
